import { Pencil, Shield, Trash2, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Role } from "../types";

interface RolesTableProps { roles: Role[]; isLoading: boolean; onEdit: (role: Role) => void; onDelete: (role: Role) => void; onAdd: () => void; }

function deleteReason(role: Role): string | undefined {
  if (role.isSystemRole) return "System roles cannot be deleted";
  if (role.userCount > 0) return "Reassign active users before deleting this role";
  return undefined;
}

export function RolesTable({ roles, isLoading, onEdit, onDelete, onAdd }: RolesTableProps) {
  if (isLoading) return <div className="overflow-hidden rounded-md border border-slate-200 dark:border-slate-700">{Array.from({ length: 5 }, (_, index) => <div key={index} className="h-16 animate-pulse border-b border-slate-200 bg-white last:border-0 dark:border-slate-700 dark:bg-slate-800" />)}</div>;
  if (!roles.length) return <div className="rounded-md border border-dashed border-indigo-200 bg-white py-16 text-center dark:border-slate-700 dark:bg-slate-900"><Shield className="mx-auto h-9 w-9 text-slate-400" /><h2 className="mt-4 font-semibold">No roles yet</h2><p className="mt-1 text-sm text-slate-500">Create the first role to start assigning access.</p><Button className="mt-5 bg-blue-700 hover:bg-blue-800" onClick={onAdd}>+ Add Role</Button></div>;

  return <div className="overflow-x-auto rounded-md border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-100 text-[9px] font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-700 dark:text-slate-300"><tr><th className="px-4 py-2.5">Role Name</th><th className="px-4 py-2.5">Description</th><th className="px-4 py-2.5">Permissions</th><th className="px-4 py-2.5">Assigned Users</th><th className="px-4 py-2.5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-slate-700">{roles.map((role) => {
    const reason = deleteReason(role); const initial = role.name.charAt(0).toUpperCase(); const percentage = role.totalPermissions ? Math.round((role.permissionCount / role.totalPermissions) * 100) : 0;
    return <tr key={role.id} className="bg-white dark:bg-slate-800"><td className="px-4 py-2.5"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded bg-blue-700 text-[10px] font-semibold text-white">{initial}</span><div><div className="flex items-center gap-1.5 font-semibold text-slate-800 dark:text-slate-100">{role.name}<span className={role.isSystemRole ? "rounded bg-blue-100 px-1 py-0.5 text-[8px] font-bold text-blue-700 dark:bg-blue-950 dark:text-blue-300" : "rounded bg-purple-100 px-1 py-0.5 text-[8px] font-bold text-purple-700 dark:bg-purple-950 dark:text-purple-300"}>{role.isSystemRole ? "SYSTEM" : "CUSTOM"}</span></div><p className="mt-0.5 text-[9px] text-slate-500 dark:text-slate-400">{role.roleSlug}</p></div></div></td><td className="max-w-64 truncate px-4 py-2.5 text-[10px] text-slate-600 dark:text-slate-300">{role.description || "—"}</td><td className="px-4 py-2.5"><div className="flex items-center gap-2"><div className="h-1.5 w-20 overflow-hidden rounded-full bg-blue-100 dark:bg-slate-700"><div className="h-full rounded-full bg-blue-700 dark:bg-blue-500" style={{ width: `${percentage}%` }} /></div><span className="text-[10px] font-semibold text-slate-700 dark:text-slate-200">{role.permissionCount}/{role.totalPermissions}</span></div></td><td className="px-4 py-2.5">{role.userCount ? <span className="flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-[8px] text-blue-700">U</span>{role.userCount} users</span> : <span className="flex items-center gap-1 text-[10px] text-slate-500 dark:text-slate-400"><UserRound className="h-3 w-3" />Unassigned</span>}</td><td className="px-4 py-2.5"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon" aria-label={`Edit ${role.name}`} className="h-7 w-7 dark:text-slate-200" onClick={() => onEdit(role)}><Pencil className="h-3 w-3" /></Button><span title={reason}><Button variant="ghost" size="icon" aria-label={`Delete ${role.name}`} disabled={Boolean(reason)} className="h-7 w-7 text-destructive hover:text-destructive" onClick={() => onDelete(role)}><Trash2 className="h-3 w-3" /></Button></span></div></td></tr>;
  })}</tbody></table><div className="border-t border-slate-200 px-4 py-2 text-[9px] text-slate-500 dark:border-slate-700 dark:text-slate-400">Showing {roles.length} registered role{roles.length === 1 ? "" : "s"}</div></div>;
}
