import type { InstitutionsData } from "../types";

export const MOCK_INSTITUTIONS_DATA: InstitutionsData = {
	total: 12,
	active: 8,
	trial: 3,
	totalUsers: 18420,
	newThisMonth: 2,
	fullyOperationalPercentage: 66.7,
	expiringIn3Days: 1,
	sla: 99.8,
	institutions: [
		{
			id: "1",
			name: "SMA Negeri 1 Surabaya",
			code: "SMANI-SBY",
			location: "Surabaya, Jawa Timur",
			type: "Sekolah",
			package: "Enterprise",
			users: 1450,
			courses: 84,
			status: "Aktif",
		},
		{
			id: "2",
			name: "Universitas Nusantara",
			code: "UNUS-JKT",
			location: "Jakarta Pusat, DKI Jakarta",
			type: "Kampus",
			package: "Enterprise",
			users: 8920,
			courses: 312,
			status: "Aktif",
		},
		{
			id: "3",
			name: "PT Karya Mandiri",
			code: "KM-CORP",
			location: "Bandung, Jawa Barat",
			type: "Perusahaan",
			package: "Pro",
			users: 420,
			courses: 28,
			status: "Trial (14 hari)",
		},
		{
			id: "4",
			name: "SMK Telkom Sidoarjo",
			code: "TELKOM-SDA",
			location: "Sidoarjo, Jawa Timur",
			type: "Sekolah",
			package: "Pro",
			users: 2150,
			courses: 110,
			status: "Aktif",
		},
		{
			id: "5",
			name: "Politeknik Bahari",
			code: "POLBAH-SMG",
			location: "Semarang, Jawa Tengah",
			type: "Kampus",
			package: "Starter",
			users: 850,
			courses: 45,
			status: "Nonaktif",
		},
		{
			id: "6",
			name: "Lembaga Bahasa Cakrawala",
			code: "LBC-YOG",
			location: "DI Yogyakarta",
			type: "Lembaga Kursus",
			package: "Pro",
			users: 630,
			courses: 19,
			status: "Trial",
		},
	],
};
